### ISSUE TITLE
memory leak in imagew-cmd

### ISSUE THREAD

**Issue by bestshow** [jsummers/imageworsener#10]
on ImageWorsener 1.3.0

#imagew $FILE out.png
=================================================================
==37530==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8651115 byte(s) in 1 object(s) allocated from:
    #0 0x4e0ad6 in malloc /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x529b7b in my_mallocfn /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:794:9
    #2 0x5aa33a in iw_malloc_ex /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-util.c:48:8
    #3 0x5aa48a in iw_malloc_large /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-util.c:77:9
    #4 0x56ffe4 in bmpr_read_uncompressed /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:665:32
    #5 0x5698be in iwbmp_read_bits /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:910:7
    #6 0x5672e8 in iw_read_bmp_file /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:980:6
    #7 0x566c20 in iw_read_file_by_fmt /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-allfmts.c:66:12
    #8 0x519fbe in iwcmd_run /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:1191:6
    #9 0x516623 in iwcmd_main /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:3018:7
    #10 0x5164f1 in main /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:3067:9
    #11 0x7fc89228fb34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

SUMMARY: AddressSanitizer: 8651115 byte(s) leaked in 1 allocation(s).

testcase:
https://github.com/bestshow/p0cs/blob/master/1048-memoryleak-imagew-cmd

**Comment by jsummers** [comment]
Should be fixed by commit 49912f8e57
