### ISSUE TITLE
memory leak in imagew-cmd

### ISSUE THREAD

**Issue by bestshow** [jsummers/imageworsener#18]
on ImageWorsener 1.3.0

#imagew $FILE out.pnm
=================================================================
==22878==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40000 byte(s) in 1 object(s) allocated from:
    #0 0x7f1ac252dbb8 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x404b65 in my_mallocfn src/imagew-cmd.c:794
    #2 0x46a79c in iw_malloc_ex src/imagew-util.c:48
    #3 0x46a8a7 in iw_malloc_large src/imagew-util.c:77
    #4 0x44f297 in iwgif_init_screen src/imagew-gif.c:498
    #5 0x4501d7 in iwgif_read_image src/imagew-gif.c:654
    #6 0x450915 in iwgif_read_main src/imagew-gif.c:726
    #7 0x450cde in iw_read_gif_file src/imagew-gif.c:775
    #8 0x43b243 in iw_read_file_by_fmt src/imagew-allfmts.c:61
    #9 0x408025 in iwcmd_run src/imagew-cmd.c:1191
    #10 0x413bfb in iwcmd_main src/imagew-cmd.c:3018
    #11 0x413cde in main src/imagew-cmd.c:3067
    #12 0x7f1ac1734b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

SUMMARY: AddressSanitizer: 40000 byte(s) leaked in 1 allocation(s).

testcase:
https://github.com/bestshow/p0cs/blob/master/topnm-memory-leak-in-imagew-cmd

**Comment by jsummers** [comment]
Should be fixed by commit 5fa4864666.
