### ISSUE TITLE
 infinite loop in src/imagew-jpeg.c: my_skip_input_data_fn

### ISSUE THREAD

**Issue by oddcoder** [jsummers/imageworsener#26]
Done via fuzzed JPEG on master
![1](https://cloud.githubusercontent.com/assets/10424605/26028178/9b1f87c4-3823-11e7-85d8-2136f4a9ad59.jpg)

`my_skip_input_data_fn` tries to skip 0x8000 bytes which is bigger than the file size thus leading to infinite loop trying to reread from the buffer
I believe if reading failed there isn't too much that can be done to save the situation
this is my suggested edit
``` diff
diff --git a/src/imagew-jpeg.c b/src/imagew-jpeg.c
index 43bf946..e0cbf2a 100644
--- a/src/imagew-jpeg.c
+++ b/src/imagew-jpeg.c
@@ -333,6 +333,9 @@ static void my_skip_input_data_fn(j_decompress_ptr cinfo, long num_bytes)
 
                rctx->pub.next_input_byte = rctx->buffer;
                rctx->pub.bytes_in_buffer = bytesread;
+               if (bytesread == 0) {
+                       return;
+               }
        }
 }
```

**Comment by jsummers** [comment]
Should be fixed by commit 62bfbfb152.
