### ISSUE TITLE
uninitialized variable might be returned in src/imagew-gif.c: iwgif_read_graphic_control_ext()

### ISSUE THREAD

**Issue by shqking** [jsummers/imageworsener#28]
In function iwgif_read_graphic_control_ext() at file src/imagew-git.c, variable **retval** is uninitialized.

`static int iwgif_read_graphic_control_ext(struct iwgifrcontext *rctx)
{
	int retval;

	// Read 6 bytes:
	//  The first is the subblock size, which must be 4.
	//  The last is the block terminator.
	//  The middle 4 contain the actual data.
	if(!iwgif_read(rctx,rctx->rbuf,6)) goto done;

	if(rctx->rbuf[0]!=4) goto done;
	if(rctx->rbuf[5]!=0) goto done;
	rctx->has_transparency = (int)((rctx->rbuf[1])&0x01);
	if(rctx->has_transparency) {
		rctx->trans_color_index = (int)rctx->rbuf[4];
	}

	retval=1;
done:
	return retval;
}`

If any of branches at line 154, 156 and 157, take the true branch, the program will jump to line 164 and this uninitialized stack variable **retval** is returned, which might cause unexpected consequence.

One possible fix I suggested here is to initialize **retval** as 0.

**Comment by shqking** [comment]
Note that this issue was found with Clang Static Analyzer.

**Comment by jsummers** [comment]
Fixed by commit edf0db37b2.
