### ISSUE TITLE
libtool version-info number?

### ISSUE THREAD

**Issue by jsummers** [jsummers/imageworsener#38]
What should the libtool "-version-info" or "-release" number be set to in the next release? If you care, please comment.

Years ago, I gave up trying to keep track of API changes. I did the rude but correct thing, and changed from `LDFLAGS=-version-info x:x:x`, to `LDFLAGS=-release y.y.y`.

I'm willing to switch back to -version-info, but I don't know what to set it to, so as not cause problems for someone. Tentative plan is "-version-info 3:0:0".

[Libtool documentation](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)

History:
 v1.0.0: -version-info 0:0:0
 v1.1.0: -version-info 1:0:0
 v1.2.0: -version-info 2:0:1
 v1.3.0: -release 1.2.0
 v1.3.1: -release 1.3.1
 v1.3.2: -release 1.3.2
 v1.3.3: -release 1.3.3

**Comment by zvezdochiot** [comment]
Here we need a more specific description of the "rake" that you came across. For example, I don't know what this is about.
