### ISSUE TITLE
Contributing simple Linux CI based on GitHub Actions via pull request welcome?

### ISSUE THREAD

**Issue by hartwork** [jsummers/imageworsener#45]
Hi!

I noticed that this repository does not have any CI so that currently pull requests could in theory break compilation unnoticed any time even with careful review. Use of GitHub Actions would be free of cost for you, works well, and only requires addition of a single YAML file to activate. I'm thinking of an approach similar to https://github.com/projectM-visualizer/frontend-libvisual-plug-in/blob/master/.github/workflows/linux.yml , aiming to cover at least GCC 12 and Clang 17 here. What do you think? 

Best, Sebastian

**Comment by jsummers** [comment]
I appreciate the suggestion and offer. I'll give it some more thought, but I don't think I'm prepared to do that at this time.

**Comment by hartwork** [comment]
@jsummers to avoid misunderstandings, the plan was to provide a pull request for you so you would not need to "do" anything in the sense of building things and the level of detail in review would be up to you. Did you mean to say you're not prepared for a repository with active CI or no prepared for building CI yourself? Would be great to be sure, thanks!

**Comment by jsummers** [comment]
I don't want to selfishly dismiss this out of hand, if it would be useful to other people.

But I'm just not interested in taking the time to learn about GitHub Actions right now. I'm uneasy about committing magic files to my project, without a good understanding of what I'd be getting into.

**Comment by hartwork** [comment]
@jsummers okay, I consider https://github.com/projectM-visualizer/frontend-libvisual-plug-in/blob/master/.github/workflows/linux.yml more of a YAML shell script rather than magic, but I will not push for it any further then, I understand and respect the need to understand contributions on detail level. Whenever you change your mind, let me know, I'm happy to do free-of-cost voice call consulting on basic GitHub Actions to get you to detail level understanding whenever you're ready. Have a nice day!

**Comment by hartwork** [comment]
No interest apparently, closing to keep my https://github.com/issues clean…
