### ISSUE TITLE
Color tone is changed after resize image

### ISSUE THREAD

**Issue by kakashi0807** [jsummers/imageworsener#7]
Please check image before and after resizing
![homescreen-01-before](https://cloud.githubusercontent.com/assets/4075484/18340246/20fbb2d2-75ce-11e6-9598-1263f22f944f.jpg)
![homescreen-02-after](https://cloud.githubusercontent.com/assets/4075484/18340247/20ffd5a6-75ce-11e6-9575-81ca76d6c7e8.jpg)

**Comment by jsummers** [comment]
In the image viewers I tried, the colors look the same to me.

The source image is a CMYK image with an ICC profile. IW doesn't support ICC profiles, and only supports CMYK by converting it to RGB in a fairly simplistic way (i.e., without using the color profile). So, it wouldn't surprise me if the colors look different in viewers that support advanced color management.

**Comment by jsummers** [comment]
I don't have enough information to reproduce this, so closing it for now.
