### ISSUE TITLE
NULL pointer dereference in iwbmp_read_info_header

### ISSUE THREAD

**Issue by bestshow** [jsummers/imageworsener#8]
on ImageWorsener 1.3.0

#imagew $FILE out.png
=================================================================
==37735==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000568328 bp 0x7fffaaf36fb0 sp 0x7fffaaf36d80 T0)
==37735==The signal is caused by a READ memory access.
==37735==Hint: address points to the zero page.
    #0 0x568327 in iwbmp_read_info_header /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:419:2
    #1 0x567205 in iw_read_bmp_file /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:970:6
    #2 0x566c20 in iw_read_file_by_fmt /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-allfmts.c:66:12
    #3 0x519fbe in iwcmd_run /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:1191:6
    #4 0x516623 in iwcmd_main /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:3018:7
    #5 0x5164f1 in main /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-cmd.c:3067:9
    #6 0x7f68fb265b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #7 0x41bbeb in _start (/home/haojun/Downloads/testopensourcecode/imageworsener-master/imagew+0x41bbeb)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/haojun/Downloads/testopensourcecode/imageworsener-master/src/imagew-bmp.c:419:2 in iwbmp_read_info_header
==37735==ABORTING

testcase:
https://github.com/bestshow/p0cs/blob/master/2712-NULL-ptr-imagew-bmp_419_2

**Comment by jsummers** [comment]
Should be fixed by commit 4500070038
